services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: webby-app
    container_name: webby-app
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
    volumes:
      - ./Install:/var/www/html
    restart: unless-stopped
